# Generated by Django 3.1.6 on 2021-02-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_compliancevalue_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancevalue',
            name='max_limit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compliancevalue',
            name='min_limit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compliancevalue',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
