# Generated by Django 3.1.6 on 2021-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20210228_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancevalue',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='element',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
