# Generated by Django 3.1.6 on 2021-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancevalue',
            name='unit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
