# Generated by Django 3.1.6 on 2021-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_compliancevalue_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancevalue',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
