# Generated by Django 3.1.6 on 2021-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20210302_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancevalue',
            name='parameter',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
