# Generated by Django 3.1.6 on 2021-03-15 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0010_auto_20210302_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(max_length=50)),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('status_of_seepage_point', models.CharField(choices=[('GD', 'Good'), ('SD', 'Slightly Disturbed'), ('BL', 'Blocked')], max_length=50)),
                ('stability_of_dam_walls', models.CharField(choices=[('STB', 'Stable'), ('SOE', 'Signs of Erosion'), ('RBT', 'Rehabilitated')], max_length=50)),
                ('holding_capacity', models.CharField(max_length=10)),
                ('current_capacity', models.CharField(max_length=10)),
                ('spillways_capacity', models.CharField(max_length=10)),
                ('spillways_stability', models.CharField(max_length=50)),
                ('signs_of_erosion_spillway_tip', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
