# Generated by Django 3.1.6 on 2021-03-17 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0011_storage_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage_facility',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Waste_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('segregation_at_source_and_bins', models.CharField(choices=[('EF', 'Effective'), ('NEF', 'Not Effective'), ('PEF', 'Partially Effective'), ('SDS', 'Sorted at Dump Site')], max_length=100)),
                ('glass_waste_source', models.CharField(max_length=10)),
                ('glass_waste_weight', models.CharField(max_length=10)),
                ('plastic_waste_source', models.CharField(max_length=10)),
                ('plastic_waste_weight', models.CharField(max_length=10)),
                ('metal_waste_source', models.CharField(max_length=10)),
                ('metal_waste_weight', models.CharField(max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slope_stabilization_and_surface_water_retention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('no_of_exposed_unstabilized_slopes', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('STD', 'Stabilized'), ('WP', 'Working Progress'), ('PEN', 'Pending'), ('OTR', 'Other')], max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Safety_training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('training', models.CharField(max_length=100)),
                ('no_of_staff', models.CharField(max_length=10)),
                ('no_of_inductions', models.CharField(max_length=10)),
                ('no_of_visitors', models.CharField(default='0', max_length=10)),
                ('duration', models.CharField(max_length=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Safety_permission_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('no_of_permits_issued', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('WES', 'Work Ended Safely'), ('WEU', 'WWork did not end safely')], max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liquid_waste_oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('discharge_point', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('MW', 'Maintenance Workshop'), ('OA', 'Other Area')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inceneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('items_incenerated', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=10)),
                ('temperature', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Health_and_hygiene_awareness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('training', models.CharField(max_length=100)),
                ('no_of_staff', models.CharField(max_length=10)),
                ('no_of_visitors', models.CharField(default='0', max_length=10)),
                ('duration', models.CharField(max_length=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grease_and_hydocarbon_spillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('storage_condition', models.CharField(choices=[('CIS', 'Completely Impervious Surface'), ('PI', 'Partially Impervious'), ('NI', 'Non Impervious'), ('SIC', 'Stored in Containment'), ('NSIC', 'Not Stored in Containment')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Energy_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('total_energy_available', models.CharField(max_length=50)),
                ('camp_consumption', models.CharField(max_length=20)),
                ('admin_consumption', models.CharField(max_length=20)),
                ('workshop_consumption', models.CharField(max_length=20)),
                ('mine_plant_consumption', models.CharField(max_length=20)),
                ('other_consumption', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('no_of_complaints', models.CharField(max_length=50)),
                ('status_of_complaints', models.CharField(choices=[('RSD', 'Resolved'), ('PEN', 'Pending'), ('OTR', 'Other')], max_length=80)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
