# Generated by Django 3.1.6 on 2021-03-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='description',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
