# Generated by Django 3.1.6 on 2021-03-21 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0014_modules_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safety_permission_system',
            name='status',
            field=models.CharField(choices=[('WES', 'Work Ended Safely'), ('WEU', 'Work did not end safely')], max_length=100),
        ),
        migrations.CreateModel(
            name='Safety_tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_1', max_length=100, null=True)),
                ('no_of_estinquishers', models.CharField(max_length=10)),
                ('fire_alarm', models.CharField(choices=[('AC', 'Active'), ('INA', 'Inactive')], max_length=100)),
                ('status_of_estinguishers', models.CharField(choices=[('MN', 'Mine'), ('PRT', 'Port'), ('SER', 'Serviced'), ('EX', 'Expired')], max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
