# Generated by Django 3.1.6 on 2021-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_auto_20210321_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_management',
            name='glass_waste_source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waste_management',
            name='metal_waste_source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waste_management',
            name='plastic_waste_source',
            field=models.CharField(max_length=100),
        ),
    ]
