# Generated by Django 3.1.6 on 2021-03-30 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0016_auto_20210322_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints_register',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='energy_management',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='grease_and_hydocarbon_spillage',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='health_and_hygiene_awareness',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='inceneration',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='liquid_waste_oil',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='safety_permission_system',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='safety_tools',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='safety_training',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='slope_stabilization_and_surface_water_retention',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='storage_facility',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.AddField(
            model_name='waste_management',
            name='location',
            field=models.CharField(default='0,0', max_length=20),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=10)),
                ('report_id', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='report_images')),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graph_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.CharField(max_length=50)),
                ('module_id', models.CharField(max_length=10)),
                ('x_column', models.CharField(blank=True, max_length=20, null=True)),
                ('y_column', models.CharField(blank=True, max_length=20, null=True)),
                ('predictive', models.BooleanField()),
                ('active', models.CharField(max_length=10)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
