# Generated by Django 3.1.6 on 2021-03-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_auto_20210330_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints_register',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='energy_management',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='grease_and_hydocarbon_spillage',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='health_and_hygiene_awareness',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='inceneration',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='liquid_waste_oil',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='safety_permission_system',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='safety_tools',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='safety_training',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='slope_stabilization_and_surface_water_retention',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='storage_facility',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
        migrations.AlterField(
            model_name='waste_management',
            name='location',
            field=models.CharField(default='0,0', max_length=200),
        ),
    ]
