# Generated by Django 3.1.6 on 2021-04-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_auto_20210331_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints_register',
            name='module',
            field=models.CharField(default='8', max_length=50),
        ),
        migrations.AddField(
            model_name='energy_management',
            name='module',
            field=models.CharField(default='7', max_length=50),
        ),
        migrations.AddField(
            model_name='grease_and_hydocarbon_spillage',
            name='module',
            field=models.CharField(default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='health_and_hygiene_awareness',
            name='module',
            field=models.CharField(default='6', max_length=50),
        ),
        migrations.AddField(
            model_name='inceneration',
            name='module',
            field=models.CharField(default='4', max_length=50),
        ),
        migrations.AddField(
            model_name='liquid_waste_oil',
            name='module',
            field=models.CharField(default='5', max_length=50),
        ),
        migrations.AddField(
            model_name='modules',
            name='table',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='safety_permission_system',
            name='module',
            field=models.CharField(default='10', max_length=50),
        ),
        migrations.AddField(
            model_name='safety_tools',
            name='module',
            field=models.CharField(default='12', max_length=50),
        ),
        migrations.AddField(
            model_name='safety_training',
            name='module',
            field=models.CharField(default='11', max_length=50),
        ),
        migrations.AddField(
            model_name='slope_stabilization_and_surface_water_retention',
            name='module',
            field=models.CharField(default='9', max_length=50),
        ),
        migrations.AddField(
            model_name='storage_facility',
            name='module',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='waste_management',
            name='module',
            field=models.CharField(default='3', max_length=50),
        ),
    ]
