# Generated by Django 3.1.6 on 2021-04-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_auto_20210402_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceneration',
            name='items_incenerated',
            field=models.CharField(max_length=200),
        ),
    ]
