# Generated by Django 3.1.6 on 2021-04-13 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0021_graph_builder_field_graph_config_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph_builder_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_fields', models.TextField(blank=True, null=True)),
                ('active', models.CharField(max_length=10)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graphbuilderuser', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graphbuildermodules', to='analytics.modules')),
            ],
        ),
    ]
