# Generated by Django 3.1.6 on 2021-04-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph_config',
            name='x_column',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='graph_config',
            name='y_column',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
