# Generated by Django 3.1.6 on 2021-04-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_auto_20210414_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph_config',
            name='predictive',
            field=models.BooleanField(default=False),
        ),
    ]
