# Generated by Django 3.1.6 on 2021-04-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_auto_20210414_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_config',
            name='graph_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
