# Generated by Django 3.1.6 on 2021-05-14 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0029_conveyers_fuelfarm_georeferencepoints_warehouse_workenvcompliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_18', max_length=100, null=True)),
                ('incident_category', models.CharField(choices=[('PERSONAL INJURY', 'Personal Injury'), ('PROPERTY DAMAGE', 'Property Damage'), ('FIRES', 'Fires'), ('LOSS TO PROCESS', 'Loss to Process'), ('ENVIRONMENT', 'Environment'), ('NEAR MISS', 'Near Miss'), ('COMMUNITY', 'Community'), ('DEATH', 'Death')], max_length=100)),
                ('incident_location', models.CharField(max_length=100)),
                ('victim_name', models.CharField(max_length=200)),
                ('incident_start', models.DateTimeField(auto_now=True)),
                ('incident_end', models.DateTimeField(auto_now=True)),
                ('cause_of_incident', models.TextField(blank=True, null=True)),
                ('actions_taken_immediately', models.TextField(blank=True, null=True)),
                ('further_actions_taken', models.TextField(blank=True, null=True)),
                ('corrective_measures', models.TextField(blank=True, null=True)),
                ('responsible_person', models.CharField(max_length=200)),
                ('location', models.CharField(default='0,0', max_length=200)),
                ('comment', models.TextField(blank=True, null=True)),
                ('module', models.CharField(default='17', max_length=50)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
