# Generated by Django 3.1.6 on 2021-05-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0030_incidentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='module',
            field=models.CharField(default='18', max_length=50),
        ),
    ]
