# Generated by Django 3.1.6 on 2021-05-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0031_auto_20210514_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
