# Generated by Django 3.1.6 on 2021-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0032_modules_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='module',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
