# Generated by Django 3.1.6 on 2021-05-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0033_auto_20210516_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='report',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
