# Generated by Django 3.1.6 on 2021-05-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0034_auto_20210516_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelfarm',
            name='impervious_status',
            field=models.CharField(choices=[('NOT_IMPERVIOUS', 'Not Impervious'), ('IMPERVIOUS', 'Impervious'), ('SEMI_IMPERVIOUS', 'Semi Impervious')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelfarm',
            name='spillage_status',
            field=models.CharField(choices=[('NO_SPILLAGE', 'No Spillage'), ('HIGH_SPILLAGE', 'High Spillage'), ('LOW_SPILLAGE', 'Low Spillage')], max_length=100),
        ),
    ]
