# Generated by Django 3.1.6 on 2021-05-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0036_auto_20210516_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationviewer',
            name='userid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
