# Generated by Django 3.1.6 on 2021-05-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0037_auto_20210517_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationviewer',
            name='notificationsId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
