# Generated by Django 3.1.6 on 2021-05-17 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0038_auto_20210517_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationviewer',
            name='userid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='notificationsvieweruser', to='auth.user'),
            preserve_default=False,
        ),
    ]
