# Generated by Django 3.1.6 on 2021-05-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0039_auto_20210517_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='default_report_path',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
