# Generated by Django 3.1.6 on 2021-05-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0041_auto_20210518_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationviewer',
            name='notificationsId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
