# Generated by Django 3.1.6 on 2021-05-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0043_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_for',
            field=models.CharField(max_length=100),
        ),
    ]
