# Generated by Django 3.1.6 on 2021-05-29 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0044_auto_20210523_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=50, null=True)),
                ('group_type', models.CharField(max_length=10)),
                ('module', models.CharField(blank=True, max_length=10, null=True)),
                ('x_column', models.CharField(blank=True, max_length=50, null=True)),
                ('y_column', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.IntegerField(default=1)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_table', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
