# Generated by Django 3.1.6 on 2021-06-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0045_custom_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints_register',
            name='status_of_complaints',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Pending', 'Pending'), ('Other', 'Other')], max_length=80),
        ),
        migrations.AlterField(
            model_name='fuelfarm',
            name='impervious_status',
            field=models.CharField(choices=[('Not Impervious', 'Not Impervious'), ('Impervious', 'Impervious'), ('Semi Impervious', 'Semi Impervious')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelfarm',
            name='spillage_status',
            field=models.CharField(choices=[('No Spillage', 'No Spillage'), ('High Spillage', 'High Spillage'), ('Low Spillage', 'Low Spillage')], max_length=100),
        ),
        migrations.AlterField(
            model_name='grease_and_hydocarbon_spillage',
            name='storage_condition',
            field=models.CharField(choices=[('Completely Impervious Surface', 'Completely Impervious Surface'), ('Partially Impervious', 'Partially Impervious'), ('Non Impervious', 'Non Impervious'), ('Stored in Containment', 'Stored in Containment'), ('Not Stored in Containment', 'Not Stored in Containment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='liquid_waste_oil',
            name='source',
            field=models.CharField(choices=[('Maintenance Workshop', 'Maintenance Workshop'), ('Other Area', 'Other Area')], max_length=50),
        ),
        migrations.AlterField(
            model_name='safety_permission_system',
            name='status',
            field=models.CharField(choices=[('Work Ended Safely', 'Work Ended Safely'), ('Work did not end safely', 'Work did not end safely')], max_length=100),
        ),
        migrations.AlterField(
            model_name='safety_tools',
            name='fire_alarm',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100),
        ),
        migrations.AlterField(
            model_name='safety_tools',
            name='status_of_estinguishers',
            field=models.CharField(choices=[('Mine', 'Mine'), ('Port', 'Port'), ('Serviced', 'Serviced'), ('Expired', 'Expired')], max_length=100),
        ),
        migrations.AlterField(
            model_name='slope_stabilization_and_surface_water_retention',
            name='status',
            field=models.CharField(choices=[('Stabilized', 'Stabilized'), ('Working Progress', 'Working Progress'), ('Pending', 'Pending'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='storage_facility',
            name='signs_of_erosion_spillway_tip',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='storage_facility',
            name='stability_of_dam_walls',
            field=models.CharField(choices=[('Stable', 'Stable'), ('Signs of Erosion', 'Signs of Erosion'), ('Rehabilitated', 'Rehabilitated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='storage_facility',
            name='status_of_seepage_point',
            field=models.CharField(choices=[('Good', 'Good'), ('Slightly Disturbed', 'Slightly Disturbed'), ('Blocked', 'Blocked')], max_length=50),
        ),
        migrations.AlterField(
            model_name='waste_management',
            name='segregation_at_source_and_bins',
            field=models.CharField(choices=[('Effective', 'Effective'), ('Not Effective', 'Not Effective'), ('Partially Effective', 'Partially Effective'), ('Sorted at Dump Site', 'Sorted at Dump Site')], max_length=100),
        ),
    ]
