# Generated by Django 3.1.6 on 2021-06-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0046_auto_20210601_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_table',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
