# Generated by Django 3.1.6 on 2021-06-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0047_custom_table_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workenvcompliance',
            name='estinquishers',
        ),
        migrations.AddField(
            model_name='workenvcompliance',
            name='estinguishers',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conveyers',
            name='electrical_safety_insulation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='conveyers',
            name='shower',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_category',
            field=models.CharField(choices=[('Personal Injury', 'Personal Injury'), ('Property Damage', 'Property Damage'), ('Fires', 'Fires'), ('Loss to Process', 'Loss to Process'), ('Environment', 'Environment'), ('Near Miss', 'Near Miss'), ('Community', 'Community'), ('Death', 'Death')], max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='eye_wash',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='shower',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workenvcompliance',
            name='fire_alarm',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workenvcompliance',
            name='first_aid',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workenvcompliance',
            name='flammables',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workenvcompliance',
            name='flooding',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workenvcompliance',
            name='safety_stickers',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
