# Generated by Django 3.1.6 on 2021-06-04 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0048_auto_20210604_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy_management',
            name='report_name',
            field=models.CharField(blank=True, default='REPORT_17', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='health_and_hygiene_awareness',
            name='report_name',
            field=models.CharField(blank=True, default='REPORT_6', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Water_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, default='REPORT_19', max_length=100, null=True)),
                ('location', models.CharField(default='0,0', max_length=200)),
                ('total_water_quantity_available', models.CharField(max_length=50)),
                ('camp_consumption', models.CharField(max_length=20)),
                ('admin_consumption', models.CharField(max_length=20)),
                ('workshop_consumption', models.CharField(max_length=20)),
                ('mine_plant_consumption', models.CharField(max_length=20)),
                ('cafeteria_consumption', models.CharField(max_length=20)),
                ('other_consumption', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('module', models.CharField(default='19', max_length=50)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
