# Generated by Django 3.1.6 on 2021-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0049_auto_20210604_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_config',
            name='on_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
