# Generated by Django 3.1.6 on 2021-06-08 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0050_graph_config_on_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='complaints_register',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conveyers',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='energy_management',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fuelfarm',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='georeferencepoints',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='grease_and_hydocarbon_spillage',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='health_and_hygiene_awareness',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inceneration',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='liquid_waste_oil',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notifications',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notificationviewer',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='safety_permission_system',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='safety_tools',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='safety_training',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='slope_stabilization_and_surface_water_retention',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='storage_facility',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tasks',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='waste_management',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wastedetails',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='water_management',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workenvcompliance',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, max_length=50, null=True)),
                ('report_structure', models.TextField(blank=True, null=True)),
                ('active', models.IntegerField(default=1)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
