# Generated by Django 3.1.6 on 2021-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0051_auto_20210608_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_management',
            name='organic_waste_source',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waste_management',
            name='organic_waste_weight',
            field=models.CharField(default='NULL', max_length=10),
            preserve_default=False,
        ),
    ]
