# Generated by Django 3.1.6 on 2021-06-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0052_auto_20210615_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedetails',
            name='report_name',
            field=models.CharField(blank=True, default='REPORT_NONAME', max_length=100, null=True),
        ),
    ]
