# Generated by Django 3.1.6 on 2021-06-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0053_wastedetails_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='is_fillable',
            field=models.BooleanField(default=1),
        ),
    ]
