# Generated by Django 3.1.6 on 2021-06-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0054_modules_is_fillable'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_config',
            name='predictive_balance',
            field=models.CharField(blank=True, default=5, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='graph_config',
            name='predictive_to',
            field=models.CharField(blank=True, default=5, max_length=9, null=True),
        ),
    ]
