# Generated by Django 3.1.6 on 2021-07-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0055_auto_20210621_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_config',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
