# Generated by Django 3.1.6 on 2021-08-04 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0056_graph_config_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_notes', to=settings.AUTH_USER_MODEL)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_id', to='analytics.reports')),
            ],
        ),
    ]
